config/routes.rb
Rails.application.routes.draw do
  resources :users
  root 'users#index'

  get 'user/change_password' => 'users#change_password', :as => 'change_user_password'
  put 'user/update_password' => 'users#update_password', :as => 'update_user_password'

  get 'login' => 'sessions#new'
  post 'login' => 'sessions#create'

  delete 'logout' => 'sessions#destroy'

  resources :groups
end

app/models/group.rb
class Group < ActiveRecord::Base
  validates_presence_of :name

  has_many :users, :dependent => :restrict_with_error
end

app/models/user.rb
class User < ActiveRecord::Base
	validates_presence_of :first_name, :last_name, :email, :group_id
	validates :email, uniqueness: true, format: { with: /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i, message: :invalid_format }

	has_secure_password

	belongs_to :group
	delegate :name, to: :group, prefix: true, allow_nil: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def set_order(params)
    order = 'id'
    if params.key?(:order)
      orders = []
      params[:order].each { |sort| orders << "#{params[:columns][sort[1][:column]][:data]} #{sort[1][:dir]}" }
      order = orders.join(', ')
    end
    order
  end
  
  helper_method :current_user

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
  
  def require_user
    redirect_to '/login' unless current_user
  end

end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  before_action :set_group, only: [:show, :edit, :update, :destroy]

  def index
    where = 'name iLIKE :value', {:value => "%#{params[:search][:value]}%"} if params.key?(:search)
    @groups = Group.where(where).order(set_order(params)).page(params[:start]).per(params[:length])
  end

  def show
  end

  def new
    @group = Group.new
  end

  def edit
  end

  def create
    @group = Group.new(group_params)

    respond_to do |format|
      if @group.save
        format.html { redirect_to @group }
        flash[:success] = 'Grupo criado com sucesso.'
        format.json { render :show, status: :created, location: @group }
      else
        format.html { render :new }
        format.json { render json: @group.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @group.update(group_params)
        format.html { redirect_to @group }
        flash[:success] = 'Grupo alterado com sucesso.'
        format.json { render :show, status: :ok, location: @group }
      else
        format.html { render :edit }
        format.json { render json: @group.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @group.destroy
    respond_to do |format|
      format.html { redirect_to groups_url }
      flash[:success] = 'Grupo excluído com sucesso'
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_group
      @group = Group.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def group_params
      params.require(:group).permit(:name)
    end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
    @user = User.new
  end

  def create
    @user = User.find_by_email(params[:session][:email])

    respond_to do |format|
      if @user && @user.authenticate(params[:session][:password])
        session[:user_id] = @user.id
        flash[:success] = t('flash.sucess.valid_login')
        format.html { redirect_to '/' }
      else
        flash[:danger] = t('flash.danger.invalid_login')
        format.html { render :new }
      end
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to '/'
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  before_action :require_user, only: [:index, :show, :new]

  # GET /users
  # GET /users.json
  def index
    where = 'first_name iLIKE :value OR last_name iLIKE :value OR email iLIKE :value', {:value => "%#{params[:search][:value]}%"} if params.key?(:search)
    @users = User.where(where).order(set_order(params)).page(params[:start]).per(params[:length])
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user }
        flash[:success] = t('flash.sucess.create_user')
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user }
        flash[:success] = t('flash.sucess.update_user')
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  def change_password
    @user = current_user
  end

  #
  #
  def update_password
    @user = User.find(current_user.id)
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user }
        flash[:success] = t('flash.sucess.update_password')
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url }
      flash[:success] = t('flash.sucess.delete_user')
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:first_name, :last_name, :email, :password, :password_confirmation, :group_id)
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
  def error_tag(model, attribute)
    if model.errors.has_key? attribute
      content_tag(
        :div,
        model.errors[attribute].first,
        class: 'help-block help-block-error'
      )
    end
  end
end

app/views/groups/_form.html.erb
<%= form_for(@group, html: {class: 'form-horizontal'}) do |f| %>
  <div class="field form-group <% if @group.errors.has_key? :name %>has-error<% end %>">
    <%= f.label :name, class: 'col-sm-2 control-label' %>
    <div class="col-sm-10">
      <%= f.text_field :name, class: 'form-control' %>
      <%= error_tag @group, :name %>
    </div>
  </div>

  <div class="actions form-group">
    <div class="col-sm-offset-2 col-sm-12">
      <%= f.submit nil, :class => 'btn btn-default' %>
      <%= link_to t('cancel'), groups_path, :class => 'btn btn-danger' %>
    </div>
  </div>
<% end %>

app/views/groups/edit.html.erb
<h1>Editar Grupo</h1>

<%= render 'form' %>

app/views/groups/index.html.erb
<h1>Listar Grupos</h1>

<table id="gridGroups" class="table table-condensed table-hover table-striped">
  <thead>
    <tr>
      <th>Name</th>
      <th><%= t('actions') %></th>
    </tr>
  </thead>
</table>

<div class="modal" id="delete-modal">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
        <h4 class="modal-title">Delete</h4>
      </div>
      <div class="modal-body">
        <p>You are about to delete.</p>
        <p>Do you want to proceed?</p>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Cancel</button>
        <button type="button" id="confirm-delete" class="btn btn-danger">Confirm</button>
      </div>
    </div>
  </div>
</div>


<script type="text/javascript">
  $(document).ready(function () {
    configDataTables['ajax'] = '/groups.json';
    configDataTables['columns'] = [
      {data: 'name'},
      {data: 'id'}
    ];
    configDataTables['aoColumnDefs'] = [{
      "aTargets": [1],
      "mRender": function (data, type, model) {
        return '<a href="/groups/' + data + '" style="color:black">'
            + '<span class="glyphicon glyphicon-eye-open"></span></a>'
            + '&nbsp;&nbsp;<a href="/groups/' + data + '/edit" style="color:black">'
            + '<span class="glyphicon glyphicon-edit"></a>';
      }
    }];

    configDataTables['fnDrawCallback'] = function (nRow, aData, iDisplayIndex, iDisplayIndexFull) {
      $('.confirm-delete').on('click', function (e) {
        e.preventDefault();

        var id = $(this).data('id');
        $('#delete-modal').data('id', id).modal('show');
      });
    };

    var table = $('#gridGroups').DataTable(configDataTables);

    $('#gridGroups_wrapper').addClass('form-inline');
    $('input[type="search"]').addClass('form-control');
    $('[name="gridGroups_length"]').addClass('form-control');

    $('#delete-modal').on('show', function () {
      var id = $(this).data('id');
    });

    $('#confirm-delete').click(function (e) {
      var id = $('#delete-modal').data('id');

      $.ajax({
        method: 'DELETE',
        url: '/groups/' + id,
        dataType: 'json',
        data: {'_method': 'delete'},
        success: function () {
          table.draw();
        },
        error: function (jqXHR, textStatus, errorThrown) {
          console.log(jqXHR, textStatus, errorThrown);
        }
      });
      e.preventDefault();

      $('#delete-modal').modal('hide');
    });
  });
</script>

app/views/groups/new.html.erb
<h1>Criar Grupo</h1>

<%= render 'form' %>

app/views/groups/show.html.erb
<h1>Grupo</h1>

<div class="row">
  <div class="col-sm-offset-1 col-sm-2">
    <label>Nome:</label>
  </div>
  <div class="col-sm-9">
    <%= @group.name %>
  </div>
</div>

<div class="row">
  <div class="col-sm-offset-1 col-sm-11">
    <label>Usuários:</label>
  </div>
  <table class="table table-condensed table-hover table-striped col-sm-offset-2 col-sm-10">
    <thead>
      <tr>
        <th><%= t('activerecord.attributes.user.first_name') %></th>
        <th><%= t('activerecord.attributes.user.last_name') %></th>
        <th>Email</th>
      </tr>
    </thead>
    <tbody>
      <% @group.users.each do |user| %>
        <tr>
          <td><%= user.first_name%></td>
          <td><%= user.last_name%></td>
          <td><%= user.email%></td>
        </tr>
      <%end %>
    </tbody>
  </table>
</div>

app/views/layouts/_navigation.html.erb
<nav id="w0" class="navbar navbar-default nav-bar-fixed-top" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#w0-collapse" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="/">Basic</a>
    </div>

    <div id="w0-collapse" class="navbar-collapse collapse" aria-expanded="false">
      <ul id="w1" class="navbar-nav navbar-right nav">
        <% if current_user %>
          <li class="dropdown <%=  'active' if current_page?(users_path) %>">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false"><%= t('menu.users') %> <span class="caret"></span></a>
            <ul class="dropdown-menu" role="menu">
              <li><%= link_to t('users.index.title'), users_path %></li>
              <li><%= link_to t('users.new.title'), new_user_path %></li>
            </ul>
          </li>
          <li class="dropdown <%=  'active' if current_page?(groups_path) %>">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Grupos <span class="caret"></span></a>
            <ul class="dropdown-menu" role="menu">
              <li><%= link_to 'Listar Grupos', groups_path %></li>
              <li><%= link_to 'Criar Grupo', new_group_path %></li>
            </ul>
          </li>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false"><%= current_user.first_name %> <span class="caret"></span></a>
            <ul class="dropdown-menu" role="menu">
              <li><%= link_to t('menu.edit'), edit_user_path(current_user) %></li>
              <li><%= link_to t('menu.change_password'), change_user_password_path(current_user) %></li>
              <li><%= link_to t('logout'), logout_path, method: "delete" %></li>
            </ul>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Basic</title>
    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
    <%= yield :stylesheet %>
    <%= csrf_meta_tags %>
  </head>
  <body>

    <div class="wrap">
      <%= render 'layouts/navigation' %>
      <div class="container">
        <% flash.each do |name, msg| -%>
          <div class="alert alert-dismissible <%= "alert-#{name}" %>" role="alert">
            <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
            <%= msg %>
          </div>
        <% end -%>

        <%= yield %>
        <%= yield :script %>
      </div>
    </div>
  </body>
</html>

app/views/users/_form.html.erb
<%= form_for(@user, html: {class: 'form-horizontal'}) do |f| %>
  <div class="field form-group <% if @user.errors.has_key? :first_name %>has-error<% end %>">
    <%= f.label :first_name, class: 'col-sm-2 control-label' %>
    <div class="col-sm-10">
      <%= f.text_field :first_name, class: 'form-control' %>
      <%= error_tag @user, :first_name %>
    </div>
  </div>

  <div class="field form-group <% if @user.errors.has_key? :last_name %>has-error<% end %>">
    <%= f.label :last_name, class: 'col-sm-2 control-label' %>
    <div class="col-sm-10">
      <%= f.text_field :last_name, class: 'form-control' %>
      <%= error_tag @user, :last_name %>
    </div>
  </div>

  <div class="field form-group <% if @user.errors.has_key? :email %>has-error<% end %>">
    <%= f.label :email, class: 'col-sm-2 control-label' %>
    <div class="col-sm-10">
      <%= f.text_field :email, class: 'form-control' %>
      <%= error_tag @user, :email %>
    </div>
  </div>

  <% if current_page?(new_user_path) %>
    <div class="field form-group <% if @user.errors.has_key? :password %>has-error<% end %>">
      <%= f.label :password, class: 'col-sm-2 control-label' %>
      <div class="col-sm-10">
        <%= f.password_field :password, class: 'form-control' %>
        <%= error_tag @user, :password %>
      </div>
    </div>
  <% end %>

  <div class="field form-group <% if @user.errors.has_key? :group_id %>has-error<% end %>">
    <%= f.label :group_id, class: 'col-sm-2 control-label' %>
    <div class="col-sm-10">
      <%= f.collection_select :group_id, Group.order(:name), :id, :name, {}, {class: "form-control"} %>
      <%= error_tag @user, :group_id %>
    </div>
  </div>

  <div class="actions form-group">
    <div class="col-sm-offset-2 col-sm-12">
      <%= f.submit nil, :class => 'btn btn-default' %>
      <%= link_to t('cancel'), users_path, :class => 'btn btn-danger' %>
    </div>
  </div>

<% end %>

app/views/users/change_password.html.erb
<h1><%= t '.title' %></h1>

<%= form_for(@user, url: {action: 'update_password'}, html: {method: 'put', class: 'form-horizontal'}) do |f| %>

  <div class="field form-group <% if @user.errors.has_key? :current_password %>has-error<% end %>">
    <%= f.label t('current_password'), class: 'col-sm-2 control-label' %>
    <div class="col-sm-10">
      <%= f.password_field :current_password, class: 'form-control' %>
      <%= error_tag @user, :current_password %>
    </div>
  </div>

  <div class="field form-group <% if @user.errors.has_key? :password %>has-error<% end %>">
    <%= f.label :password, class: 'col-sm-2 control-label' %>
    <div class="col-sm-10">
      <%= f.password_field :password, class: 'form-control' %>
      <%= error_tag @user, :password %>
    </div>
  </div>

  <div class="field form-group <% if @user.errors.has_key? :password_confirmation %>has-error<% end %>">
    <%= f.label t('password_confirmation'), class: 'col-sm-2 control-label' %>
    <div class="col-sm-10">
      <%= f.password_field :password_confirmation, class: 'form-control' %>
      <%= error_tag @user, :password_confirmation %>
    </div>
  </div>

  <div class="actions form-group">
    <div class="col-sm-offset-2 col-sm-12">
      <%= f.submit t('update_password'), :class => 'btn btn-default' %>
      <%= link_to t('cancel'), users_path, :class => 'btn btn-danger' %>
    </div>
  </div>

<% end %>

app/views/users/edit.html.erb
<h1><%= t '.title' %></h1>

<%= render 'form' %>

app/views/users/index.html.erb
<h1><%= t '.title' %></h1>

<table id="grid" class="table table-condensed table-hover table-striped">
  <thead>
  <tr>
    <th><%= t('activerecord.attributes.user.first_name') %></th>
    <th><%= t('activerecord.attributes.user.last_name') %></th>
    <th>Email</th>
    <th><%= t('actions') %></th>
  </tr>
  </thead>
</table>

<div class="modal" id="delete-modal">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
        <h4 class="modal-title">Delete</h4>
      </div>
      <div class="modal-body">
        <p>You are about to delete.</p>
        <p>Do you want to proceed?</p>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Cancel</button>
        <button type="button" id="confirm-delete" class="btn btn-danger">Confirm</button>
      </div>
    </div>
  </div>
</div>


<script type="text/javascript">
  $(document).ready(function () {
    configDataTables['ajax'] = '/users.json';
    configDataTables['columns'] = [
      {data: 'first_name'},
      {data: 'last_name'},
      {data: 'email'},
      {data: 'id'}
    ];
    configDataTables['aoColumnDefs'] = [{
      "aTargets": [3],
      "mRender": function (data, type, model) {
        return '<a href="/users/' + data + '" style="color:black">'
            + '<span class="glyphicon glyphicon-eye-open"></span></a>'
            + '&nbsp;&nbsp;<a href="/users/' + data + '/edit" style="color:black">'
            + '<span class="glyphicon glyphicon-edit"></a>'
            + '&nbsp;&nbsp;<a href="#" class="confirm-delete" data-id="' + data + '" style="color:red">'
            + '<span class="glyphicon glyphicon-trash"></span></a>';
      }
    }];

    configDataTables['fnDrawCallback'] = function (nRow, aData, iDisplayIndex, iDisplayIndexFull) {
      $('.confirm-delete').on('click', function (e) {
        e.preventDefault();

        var id = $(this).data('id');
        $('#delete-modal').data('id', id).modal('show');
      });
    };

    var table = $('#grid').DataTable(configDataTables);

    $('#grid_wrapper').addClass('form-inline');
    $('input[type="search"]').addClass('form-control');
    $('[name="grid_length"]').addClass('form-control');

    $('#delete-modal').on('show', function () {
      var id = $(this).data('id');
    });

    $('#confirm-delete').click(function (e) {
      var id = $('#delete-modal').data('id');

      $.ajax({
        method: 'DELETE',
        url: '/users/' + id,
        dataType: 'json',
        data: {'_method': 'delete'},
        success: function () {
          table.draw();
        },
        error: function (jqXHR, textStatus, errorThrown) {
          console.log(jqXHR, textStatus, errorThrown);
        }
      });
      e.preventDefault();

      $('#delete-modal').modal('hide');
    });

  });

</script>

app/views/users/new.html.erb
<h1><%= t '.title' %></h1>

<%= render 'form' %>

app/views/users/show.html.erb
<h1><%= t '.title' %></h1>

<div class="row">
  <div class="col-sm-offset-1 col-sm-2">
    <label><%= t('activerecord.attributes.user.first_name') %>:</label>
  </div>
  <div class="col-sm-9">
    <%= @user.first_name %>
  </div>
</div>

<div class="row">
  <div class="col-sm-offset-1 col-sm-2">
    <label><%= t('activerecord.attributes.user.last_name') %>:</label>
  </div>
  <div class="col-sm-9">
    <%= @user.last_name %>
  </div>
</div>

<div class="row">
  <div class="col-sm-offset-1 col-sm-2">
    <label><%= t('activerecord.attributes.user.email') %>:</label>
  </div>
  <div class="col-sm-9">
    <%= @user.email %>
  </div>
</div>

<div class="row">
  <div class="col-sm-offset-1 col-sm-2">
    <label>Grupo:</label>
  </div>
  <div class="col-sm-9">
    <%= @user.group_name %>
  </div>
</div>